name: CI

on:

  push:

  pull_request:

  workflow_dispatch:

jobs:

  fpm:

    runs-on: ubuntu-latest

    strategy:

      matrix:

        profile: [debug, release]

    steps:

      - uses: actions/checkout@v5

      - name: Install fpm
        uses: fortran-lang/setup-fpm@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify installation; gfortran
        run: gfortran --version

      - name: Verify installation; fpm
        run: fpm --version

      - name: Check if this library can be built
        run: fpm build --profile ${{ matrix.profile }}

      - name: Test this library
        run: fpm test --profile ${{ matrix.profile }}

  ford:

    needs: [fpm]

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - uses: actions/checkout@v5

      - name: Install FORD
        run: sudo pip install ford

      - name: Verify FORD installation
        run: ford --version

      - name: Install Graphviz
        run: sudo apt-get install -y graphviz

      - name: Verify Graphviz installation
        run: dot -V

      - name: Generate documentation
        run: ford ford.md

      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: doc
          if-no-files-found: error

      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@v4
        if: ${{ github.event_name == 'push'  &&  github.ref == 'refs/heads/main' }}
        with:
          branch: github-pages
          folder: doc
